== Azure Application Configuration

Azure App Configuration provides a service to centrally manage application settings and feature flags. It's mainly tareted at applications that are distributed across cloud. Spreading Configuration across several components can lead to hard to troubleshoot errors. Use App Configuration to store all the settings for your application and secure their accesses in one place.
Configuration data stored in an App Configuration store, which includes all keys and values, is encrypted at rest and in transit. App Configuration isn't a replacement solution for Azure Key Vault. Don't store application secrets in it.

Application Configuration complements KeyVault. It makes it easier to implement the following scenarios:
*  *Centralize management and distribution* of hierarchical configuration data for different environments and geographies
*  *Dynamically change application settings* without the need to redeploy or restart an application
*  *Control feature availability* in real-time

App Configuration offers the following benefits:
* A fully managed service that can be set up in minutes
* Flexible key representations and mappings
* Tagging with labels
* Point-in-time replay of settings
* Dedicated UI for feature flag management
* Comparison of two sets of configurations on custom-defined dimensions
* Enhanced security through Azure-managed identities
* Encryption of sensitive information at rest and in transit
* Native integration with popular frameworks

For Java & SPring apps, there is a client library which Microsoft provides. https://microsoft.github.io/spring-cloud-azure/docs/azure-app-configuration/2.9.0/reference/html/index.html[Spring Cloud Azure App Configuration].
As The spring site says. "The Azure Spring Cloud App Configuration Client Library loads configurations and feature flags from the Azure App Configuration service. The client library generates PropertySource abstractions, to match those already being generated by the Spring environment such as; Environment Variables, Command-line configurations, local configuration files, and so on"

=== Configuration Keys

Configuration data is stored as key value pairs. Keys stored in App Configuration are case-sensitive, unicode-based strings. Keep this in mind when you use configuration settings within an application because some frameworks handle configuration keys case-insensitively.
Special characters of `+\*+`, `+,+`, `+\+` require escaping.
There are two general approaches to naming keys used for configuration data: flat or hierarchical. These methods are similar from an application usage standpoint, but hierarchical naming offers many advantages.
* Easier to read. Instead of one long sequence of characters, delimiters in a hierarchical key name function as spaces in a sentence.
* Easier to manage. A key name hierarchy represents logical groups of configuration data
* Easier to use. It's simpler to write a query that pattern-matches keys in a hierarchical structure and retrieves only a portion of configuration data.

Keys can be for example broken down by services (`+AppName:Service1:ApiEndpoint+`) or regions (`+AppName:Region1:DbEndpoint+`).

=== Key Labels

Key values in App Configuration can optionally have a label attribute. Labels are used to differentiate key values with the same key. A key app1 with labels A and B forms two separate keys in an App Configuration store. By default, the label for a key value is empty, or null.
Label provides a convenient way to create variants of a key. A common use of labels is to specify multiple environments for the same key. Alternatively they can be used to version the keys. You can input an application version number or a Git commit ID in labels to identify key values associated with a particular software build.


----
AppName:DbEndpoint & Label = Test
AppName:DbEndpoint & Label = Staging
----

=== Values

Values assigned to keys are also unicode strings. You can use all unicode characters for values. There's an optional user-defined content type associated with each value. Use this attribute to store information, for example an encoding scheme, about a value that helps your application to process it properly

=== Feature Management

Basic concepts:
* Feature flag
* Feature manager - application package that handles the lifecycle of all the feature flags often providing extra features like caching, updating etc.
* Filter - a rule for evaulating the state of a feature flag for example based on user group, device type, geo location

Feature flag declaration in Azure has two parts - a name and a list of one or more filters that evaluate when the flag is on. When a feature flag has multiple filters, the filter list is traversed in order until first of the filters determines the feature should be enabled. At this point the fllag is on and the remaining filters are skipped.
To use feature flags effectively, you need to externalize all the feature flags used in an application.

The feature manager supports appsettings.json as a configuration source for feature flags. The following example shows how to set up feature flags in a JSON file.

[source,json]
----
"FeatureManagement": {
    "FeatureA": true, // Feature flag set to on
    "FeatureB": false, // Feature flag set to off
    "FeatureC": {
        "EnabledFor": [
            {
                "Name": "Percentage",
                "Parameters": {
                    "Value": 50
                }
            }
        ]
    }
}
----

=== Securing the configuration

==== Customer Managed Key

App config encrypts the configuration data at rest by standard using 256 bit AES encryption key (microsoft provided). There's an option to enable *customer managed key* (probably for encryption but not sure the doc does not say it), where the RSA or RSA HSM key is stored in Key Vault and the Application Confiiguration istance (with a managed identity) will contact Key Vault to fetch that key.

==== Private Endpoints

We can also use private endpoints for Azure App Configuration to allow clients on a virtual network (VNet) to securely access data over a private link.The private endpoint uses an IP address from the VNet address space for your App Configuration store.
Firewall may be configured in such a way that it blocks any external traffic to Application Configuration.

==== Managed Identities

We can also assign a managed identity to application cofiguration, just as we do for other Azure resources, but not sure why we would do that. Doc says to access Key Vault and that's it :)
