== Key Vault

Azure Key Vault is a cloud service for securely storing and accessing secrets. A secret is anything that you want to tightly control access to, such as API keys, passwords, certificates, or cryptographic keys.

Azure Key Vault helps solve the following problems:
* *Secrets Management* Azure Key Vault can be used to Securely store and tightly control access to tokens, passwords, certificates, API keys, and other secrets
* *Key Management* - Azure Key Vault makes it easy to create and control the encryption keys used to encrypt your data.
* *Certificate Management* - Azure Key Vault is also a service that lets you easily provision, manage, and deploy public and private Secure Sockets Layer/Transport Layer Security (SSL/TLS) certificates for use with Azure and your internal connected resources

=== Tiers
* Standard - encrypts with a software key
* Premium - includes hardware security module(HSM)-protected keys

=== Benefits
* Centralized application secrets - stores secrets in one place and allows to securely reference them by url
* Securely store secrets and keys - access to secrets requires proper authZ (via RBAC or key vault access policy)
* Monitor access and use - logging may be enabled for vaults, logs can also have secured access. Azure Key Vault can be configured to:
	** Archive to a storage account.
	** Stream to an event hub.
	** Send the logs to Azure Monitor logs.
* Simplified administration of application secrets - Security information must be secured, it must follow a life cycle, and it must be highly available. Key Vault does that by:
	** Scaling up on short notice to meet your organization’s usage spikes
	** Replicating the contents of your Key Vault within a region and to a secondary region
	** Providing standard Azure administration options via the portal, Azure CLI and PowerShell
	** Automating certain tasks on certificates that you purchase from Public CAs, such as enrollment and renewal
	** RBAC probably comes into play here also.

=== Authenticating with Key Vault
To do any operations with Key Vault, you first need to authenticate to it. There are three ways to authenticate to Key Vault:
* Managed identities for Azure resources - this is a best practice approach. It gives an identity to an Azure Resource that has access to Key VAult.
* Service principal and certificate - You can use a service principal and an associated certificate that has access to Key Vault. We don't recommend this approach because the application owner or developer must rotate the certificate
* Service principal and secret - similar as above. Secret also needs to be rotated
* Seems like anothher option is to use Azure Identity SDK

==== Authenticating with REST
Access tokens must be sent to the service using the HTTP Authorization header
----
PUT /keys/MYKEY?api-version=<api_version>  HTTP/1.1
Authorization: Bearer <access_token>
----

=== Encryption of data in transit
Azure Key Vault enforces Transport Layer Security (TLS) protocol to protect data when it’s traveling between Azure Key Vault and clients.
Perfect Forward Secrecy (PFS) protects connections between customers’ client systems and Microsoft cloud services by unique keys. Connections also use RSA-based 2,048-bit encryption key lengths. This combination makes it difficult for someone to intercept and access data that is in transit.

=== Best practices
* *Use separate key vaults:* Recommended using a vault per application per environment (Development, Pre-Production and Production). This pattern helps you not share secrets across environments and also reduces the threat if there is a breach
* *Control access to your vault:* Key Vault data is sensitive and business critical, you need to secure access to your key vaults by allowing only authorized applications and users
* *Backup:* Create regular back ups of your vault on update/delete/create of objects within a Vault
* *Logging:* Be sure to turn on logging and alerts
* *Recovery options:* Turn on soft-delete and purge protection if you want to guard against force deletion of the secret.


https://learn.microsoft.com/en-us/azure/key-vault/general/developers-guide[Key vault developers guide]

----
az keyvault create --name $myKeyVault --resource-group az204-vault-rg --location $myLocation
az keyvault secret set --vault-name $myKeyVault --name "ExamplePassword" --value "hVFkk965BuUv"
az keyvault secret show --name "ExamplePassword" --vault-name $myKeyVault
----
